### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(MyTetris)
add_subdirectory(MyTetrisContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "build/Desktop_Qt_6_10_1_MinGW_64_bit-Debug/.qtc_clangd/compile_commands.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    MyTetrisplugin
    MyTetrisContentplugin
    QtQuickDesignerComponents)